/*
Created by Conner Recoskie
June 1st
This program excepts a decimal value, then converts that it binary, it excepts a
binary value and converts it to decimal, it excepts a decimal value and converts
it to hexadeciaml, and it excepts a hexideximal value and converts it to decimal
value.
*/

public class FrmConvert extends javax.swing.JFrame {
    
    /*
    decToBinary
    This method excepts a decimal number, it then calculates and returns the
    number in binary.
    Parametrers: int
    Returns: int
    */
    public static int decToBinary (int decimalValue)
    {
        // Declaring local variables to be used in the decToBinary method
        int binary = 0;
        int count = 0;
        
        while (decimalValue != 0)
        {
            int remainder = decimalValue % 2;
            double count1 = Math.pow(10, count);
            binary += remainder * count1;
            
            decimalValue /= 2;
            
            count++;
        }
        return (binary);
    }
    
    /*
    binToDecimal
    This method excepts a binary number, it then calculates and returns the 
    number in decimal.
    Parameters: int
    Returns: int
    */
    public static int binToDecimal (int binaryValue)
    {
        /* Declaring local variables to be used in the process of converting and
        to be used to hold the new decimal value */
        int decimal = 0;
        int count = 0;
        
        while (true)
        {
            if (binaryValue == 0)
            {
                break;
            }
            else
            {
                int temp = binaryValue % 10;
                decimal += temp * Math.pow(2, count);
                binaryValue = binaryValue/10;
                
                count++;
            }
        }
        return decimal;
        
    }
    /*
    decToHex
    This method excepts a decimal number, it then calculates and returns the
    number in hexadecimal.
    Parameters: int
    Returns: String
    */
  
    public static String decToHex (int decimal)
    {
        /* Declaring a local int variable to hold the remainder value in the 
           decToHex method */
        int remainder;
        
        String hexValue = "";
        
        char hexadecimal [] = {'0', '1', '2', '3', '4', '5', '6', '7','8', '9', 
                               'A', 'B', 'C','D', 'E', 'F'};
        
        while (decimal > 0)
        {
            remainder = decimal % 16;
            hexValue = hexadecimal[remainder] + hexValue;
            decimal = decimal/16;
        }
        return (hexValue);
    }
    
    /*
    hexToDec
    This method excepts a hexadecimal number, it then calculates and returns the
    number in decimal.
    Parameters: String
    Returns: int
    */
    public static int hexToDec (String hexadecimal)
    {
        /* Declaring a local String variable to be used to hold the hexadeciaml
           values. */
        String hexValues = "0123456789ABCDEF";
        
        hexadecimal = hexadecimal.toUpperCase();
        
        int decimal = 0;
        
        for (int i = 0; i < hexadecimal.length(); i++)
        {
            char characterAt = hexadecimal.charAt(i);
            int num = hexValues.indexOf(characterAt);
            decimal = 16 * decimal + num;
        }
        return (decimal);
    }
    
    
    public FrmConvert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSection1 = new javax.swing.JLabel();
        lblDec1 = new javax.swing.JLabel();
        txtDec1 = new javax.swing.JTextField();
        lblBinary = new javax.swing.JLabel();
        txtBinary = new javax.swing.JTextField();
        lblSection2 = new javax.swing.JLabel();
        lblDec2 = new javax.swing.JLabel();
        txtDec2 = new javax.swing.JTextField();
        lblHex = new javax.swing.JLabel();
        txtHexiDec = new javax.swing.JTextField();
        btnDecToBin = new javax.swing.JButton();
        btnBinToDec = new javax.swing.JButton();
        btnDecToHex = new javax.swing.JButton();
        btnHexToDec = new javax.swing.JButton();
        lblDecToBin = new javax.swing.JLabel();
        lblBinToDec = new javax.swing.JLabel();
        lblDecToHex = new javax.swing.JLabel();
        lblHexToDec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("--Number Systems--");

        lblSection1.setText("Binary and Decimal");

        lblDec1.setText("Enter a decimal number:");

        lblBinary.setText("Enter a binary number:");

        lblSection2.setText("Decimal and Hexidecimal");

        lblDec2.setText("Enter a decimal number:");

        lblHex.setText("Enter a hexidecimal number:");

        btnDecToBin.setText("Dec. To Bin.");
        btnDecToBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBinActionPerformed(evt);
            }
        });

        btnBinToDec.setText("Bin. To Dec.");
        btnBinToDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinToDecActionPerformed(evt);
            }
        });

        btnDecToHex.setText("Dec. To Hex.");
        btnDecToHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToHexActionPerformed(evt);
            }
        });

        btnHexToDec.setText("Hex. To Dec.");
        btnHexToDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHexToDecActionPerformed(evt);
            }
        });

        lblDecToBin.setText("-");

        lblBinToDec.setText("-");

        lblDecToHex.setText("-");

        lblHexToDec.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDec1)
                                    .addComponent(lblBinary))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDec1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDec2)
                                    .addComponent(lblHex))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHexiDec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDec2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBinToDec)
                            .addComponent(btnDecToHex)
                            .addComponent(btnHexToDec)
                            .addComponent(btnDecToBin))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDecToBin, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblHexToDec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDecToHex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBinToDec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(lblSection1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lblSection2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(238, 238, 238)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addComponent(lblSection1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDec1)
                    .addComponent(txtDec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecToBin)
                    .addComponent(lblDecToBin))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinary)
                    .addComponent(txtBinary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBinToDec)
                    .addComponent(lblBinToDec))
                .addGap(30, 30, 30)
                .addComponent(lblSection2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDec2)
                    .addComponent(txtDec2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecToHex)
                    .addComponent(lblDecToHex))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHex)
                    .addComponent(txtHexiDec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHexToDec)
                    .addComponent(lblHexToDec))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecToBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToBinActionPerformed
        // Declaring an int variable to hold the user input
        int dec1;
        
        /* Declaring an int variable to hold the result of calling the 
           decToBin method */
        int decToBin;
        
        try
        {
            // Getting and storing the users input in a variable
            dec1 = Integer.parseInt(txtDec1.getText());
            
            /* Calling the decToBinary method, passing it the users input. Also, 
               storing the result in a variable */
            decToBin = decToBinary(dec1);
            
            // Outputting the binary number to the GUI
            lblDecToBin.setText(String.valueOf(decToBin));
        }
        catch (NumberFormatException e)
        {
            // Outputting an error message if incorrect data is entered
            lblDecToBin.setText("Error, Incorrect input!");
        }
    }//GEN-LAST:event_btnDecToBinActionPerformed

    private void btnBinToDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinToDecActionPerformed
         /* Declaring an int variable to hold the result of calling the 
            binToDec method */
        int binToDec;
        
        // Declaring an int variable to hold the user input
        int binary;
        
        try
        {
            // Getting and storing the users input in a variable
            binary = Integer.parseInt(txtBinary.getText());

            /* Calling the binTodecimal method, passing it the users input. Also, 
               storing the result in a variable */
            binToDec = binToDecimal(binary);

            // Outputting the decimal number to the GUI
            lblBinToDec.setText(String.valueOf(binToDec));
        }
        catch (NumberFormatException e)
        {
            // Outputting an error message if incorrect data is entered
            lblBinToDec.setText("Error, Incorrect input!");
        }
    }//GEN-LAST:event_btnBinToDecActionPerformed

    private void btnDecToHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToHexActionPerformed
        /* Declaring a String variable to hold the result from calling the 
           decToHex method */
        String hexadecimal;
        
        // Declaring an int variable to hole the users input
        int hexaValue;
        
        try
        {
            // Getting and storing the users input in a variable
            hexaValue = Integer.parseInt(txtDec2.getText());

            /* Calling the decToHex method, passing it the users input. Also, 
               storing the result in a variable */
            hexadecimal = decToHex(hexaValue);

            // Outputting the hexadecimal number to the GUI
            lblDecToHex.setText(hexadecimal);
        }
        catch (NumberFormatException e)
        {
            lblDecToHex.setText("Error, Incorrect input!");
        }
    }//GEN-LAST:event_btnDecToHexActionPerformed

    private void btnHexToDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHexToDecActionPerformed
        // Declaring a string variable to hold the users input
        String hexInput;
        
        /* Declaring an int variable to hold the result from calling the 
           hexToDec method */
        int decimalValue;
        
        // Getting and storing the users input in a variable
        hexInput = txtHexiDec.getText();
        
        /* Calling the hexToDec method, passing it the users input. Also, 
           storing the result in a variable */
        decimalValue = hexToDec(hexInput);
        
        // Outputting the decimal number to the GUI
        lblHexToDec.setText(String.valueOf(decimalValue));
    }//GEN-LAST:event_btnHexToDecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConvert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConvert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBinToDec;
    private javax.swing.JButton btnDecToBin;
    private javax.swing.JButton btnDecToHex;
    private javax.swing.JButton btnHexToDec;
    private javax.swing.JLabel lblBinToDec;
    private javax.swing.JLabel lblBinary;
    private javax.swing.JLabel lblDec1;
    private javax.swing.JLabel lblDec2;
    private javax.swing.JLabel lblDecToBin;
    private javax.swing.JLabel lblDecToHex;
    private javax.swing.JLabel lblHex;
    private javax.swing.JLabel lblHexToDec;
    private javax.swing.JLabel lblSection1;
    private javax.swing.JLabel lblSection2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBinary;
    private javax.swing.JTextField txtDec1;
    private javax.swing.JTextField txtDec2;
    private javax.swing.JTextField txtHexiDec;
    // End of variables declaration//GEN-END:variables
}
